#!/bin/bash
cd ../../../
NODE_ENV=test
if [ -z "$1" ]; then
  for i in checkout confirmCheckoutComplete createService getRecentReviews getReviewScore invitation onSessionPublished onSlotActive onSlotPurchased publishPotential registerCreator registerSupporter stripeAccountOnboard writeNewReview
  do
    node node_modules/jest/bin/jest src/spec/"$i".spec.ts -c jest.config.js;
  done
elif [ "$1" == 'nock' ]; then
  for i in checkoutComplete stripeCompleteOnboard
  do
    node node_modules/jest/bin/jest src/spec/"$i".spec.ts -c jest.config.js;
  done
fi
